version: "3"

services:
    nginx:
        image: nginx:1.17-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
        - 8000:80
        volumes:
        - ./:/var/www
        - ./docker-compose/nginx:/etc/nginx/conf.d
        depends_on:
            - applaravel
            - mysql
        networks:
            - networkapp
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: code_challenge
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password
            MYSQL_ROOT_PASSWORD: db_password
        ports:
            - 3307:3306
        volumes:
            - dbdatalaravel:/var/lib/mysql
        networks:
            - networkapp
    applaravel:
        build:
            args:
                user: laraveluser
                uid: 1000
            context: .
            dockerfile: ./Dockerfile
        container_name: applaravel
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - networkapp
networks:
    networkapp:

volumes:
    dbdatalaravel:
